import pandas as pd
import matplotlib.pyplot as plt 

df = pd.read_csv(r'C:\Users\tanti\Downloads\Bank_Churn (1).csv') 
print(df.head())
print(df.tail())
print (df.shape)
print(df.isna().sum().sum())
print(df.duplicated().sum())
print(df.drop_duplicates())
print(df['Geography'].unique())
print(df['Geography'].value_counts())
print(df['Geography'].value_counts())
print(df['Age'].mean())
print(df['CreditScore'].mean())
print(df['Balance'].max())
print(df['Balance'].min())
print(df['Balance'].median())
print(df['EstimatedSalary'].std())
print(df[['Age','Balance']])
print(df['Surname']) 
print(df.iloc[0:5, 0:3])
print(df.loc[df['Age'] > 50, ['CustomerId', 'Age', 'Exited']])
print(df[df['Age']>50])
print(df[df['CreditScore']<600])
print(df[df['Geography']== 'Germany'])
print(df[(df['Geography'] == 'France') & (df['IsActiveMember'] == 1)])
print(df[df['Geography'].isin(['France', 'Germany'])])
print(df[df['Balance']>1000])
print(df[df['NumOfProducts']==3])
print(df.sort_values('Balance', ascending = False))
print(df.sort_values(['Geography', 'Balance'], ascending=[True, False]))
print(filtered = df[(df['CreditScore'] >= 700) & (df['IsActiveMember'] == 1)])
